[package]

name = "air"
version = "0.0.1"
authors = [ "Emerson Knapp <emerson.b.knapp@gmail.com>" ]

[dependencies.sdl2]
version="0.29"
default-features=false
features = ["ttf","image","gfx","mixer"]
